### ISSUE TITLE
Update hook not working

### ISSUE THREAD

**Issue by amitpammu** [nicolascava/sequelize-i18n#2]
I had tried to update the  data but somehow it is not working.

const Op = Sequelize.Op

db.Product.update({
  firstName: "test",
}, {
    where: {
      email: {
        [Op.eq]: "test@gmail.com"
      }
    }
  }).then((result) => {
    //result.product_i18ns = [ {firstName : "french name" , language_id : "FR" } ]
    
  }).catch((e) => {
    console.log(e);
  });

it is not updating any records.

**Comment by kurisutofu** [comment]
I believe you have to specify the language in the options.

**Comment by nicolascava** [comment]
I'm sorry, but I close this issue because it's been months since the last message.
