### ISSUE TITLE
Project doesn't start with sequelize v5

### ISSUE THREAD

**Issue by kurisutofu** [nicolascava/sequelize-i18n#3]
I am getting the following error when running the project.
I believe it may be due to the version v5 of sequelize and a different way of handling hooks (didn't read in details though).

```
hookTypes[hookType].proxies
                      ^

TypeError: Cannot read property 'proxies' of undefined
```

**Comment by aftabaig** [comment]
I am getting the same issue. Any updates?

**Comment by kurisutofu** [comment]
I have updated the code and created a PR.

**Comment by jorgitoml** [comment]
Hi @kurisutofu 
I've checked your code and I'm getting this error:
{
    "err": {
        "name": "SequelizeDatabaseError",
        "parent": {
            "code": "ER_NO_DEFAULT_FOR_FIELD",
            "errno": 1364,
            "sqlState": "HY000",
            "sqlMessage": "Field 'name' doesn't have a default value",
            "sql": "INSERT INTO `cat_country` (`id_country`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?);",
            "parameters": [
                "2020-02-10 16:39:14",
                "2020-02-10 16:39:14"
            ]
        },
        "original": {
            "code": "ER_NO_DEFAULT_FOR_FIELD",
            "errno": 1364,
            "sqlState": "HY000",
            "sqlMessage": "Field 'name' doesn't have a default value",
            "sql": "INSERT INTO `cat_country` (`id_country`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?);",
            "parameters": [
                "2020-02-10 16:39:14",
                "2020-02-10 16:39:14"
            ]
        },
        "sql": "INSERT INTO `cat_country` (`id_country`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?);",
        "parameters": [
            "2020-02-10 16:39:14",
            "2020-02-10 16:39:14"
        ]
    }
}

Any clue?

**Comment by hardikverma24** [comment]
@kurisutofu I am also getting the same issue when I updated the sequelize version. Can you please provide the link of the PR in which you resolved the issue

**Comment by andresdaguilar** [comment]
Having the same issue here. Was it fixed @kurisutofu @nicolascava ?

**Comment by kurisutofu** [comment]
Hi @hardikverma24 , @andresdaguilar ,

This is the pull request: https://github.com/nicolascava/sequelize-i18n/pull/4

However, I believe it was merged so it should be in the latest version.
I haven't tested this recently so not sure though.

**Comment by hardikverma24** [comment]
Thanks @kurisutofu

**Comment by hardikverma24** [comment]
@kurisutofu The proxies issue is resolved but now a new error is coming with sequelize v5. I'm new to sequelize Please help. 
**error** - 

> Failed to load undefined:  TypeError: Class constructor Account cannot be invoked without 'new'
    at Sequelize.import (/home/springrole/toro/backend/node_modules/sequelize/lib/sequelize.js:486:38)
    at /home/springrole/toro/backend/models/index.js:21:42
    at Array.forEach (<anonymous>)
    at module.exports (/home/springrole/toro/backend/models/index.js:17:13)
    at module.exports (/home/springrole/toro/backend/index.js:38:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**this is my model file** - 
`const Sequelize = require('sequelize');

module.exports = 
    class Account extends Sequelize.Model{
        static init(sequelize){
        return super.init({
            AccountId: {
                type: Sequelize.BIGINT(11),
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            Currency: {
                type: Sequelize.STRING,
                allowNull: true
            },
            CompanyId: {
                type: Sequelize.BIGINT(11),
                allowNull: false,
                references: {
                    model: 'Company',
                    key: 'CompanyId'
                }
            },
            CurrentBalance: {
                type: Sequelize.STRING,
                allowNull: true
            },
            Classification: {
                type: Sequelize.STRING,
                allowNull: false
            },
            AccountType: {
                type: Sequelize.STRING,
                allowNull: false
            },
            Account: { //Name
                type: Sequelize.STRING,
                allowNull: false
            },
            IsActive: {
                type: Sequelize.BOOLEAN,
                allowNull: false,
                defaultValue: 1
            },
            CreatedBy: {
                type: Sequelize.UUID,
                allowNull: true
            },
            UpdatedBy: {
                type: Sequelize.UUID,
                allowNull: true
            },
            MappedQuickbookId:{
                type: Sequelize.BIGINT(11),
                allowNull: true,
                references: {
                    model: 'QuickbookAccount',
                    key: 'QuickbookAccountId'
                } 
            }
        },
        {
            tableName: 'account',
            createdAt: 'CreatedOn',
            updatedAt: 'UpdatedOn',
            paranoid: true,
            deletedAt: 'DeletedOn',
            sequelize
        });
    }
    
    static associate(models) {
        this.belongsTo(models.Company, {
            foreignKey: 'CompanyId'
        });
        this.belongsTo(models.QuickbookAccount, {
            foreignKey: 'MappedQuickbookId',
            targetKey: 'QuickBookAccountId'
        });
    }
};
`
**this is my index file** - `var fs = require('fs');

var path = require('path');

var _ = require('underscore');

module.exports = function(sequelize, wagner) {
  var excludeFiles;
  this.sequelize = sequelize;
  this.wagner = wagner;
  this.models = {};
  excludeFiles = ["index.js"];
  fs.readdirSync(__dirname).filter((function(_this) {
    return function(file) {
      return (file.indexOf(".") !== 0) && excludeFiles.indexOf(file) < 0;
    };
  })(this)).forEach((function(_this) {
    return function(file) {
      var err, model;
      try {
        model = _this.sequelize["import"](path.join(__dirname, file));
        return _this.models[model.name] = new model;
      } catch (_error) {
        err = _error;
        console.log("Failed to load " + model + ": ", err);
        return console.log(err.message);
      }
    };
  })(this));
  Object.keys(this.models).forEach((function(_this) {
    return function(modelName) {
      if ("associate" in _this.models[modelName]) {
        return _this.models[modelName].associate(_this.models);
      }
    };
  })(this));
  _.each(this.models, (function(_this) {
    return function(value, key) {
      return _this.wagner.factory(key, function() {
        return value;
      });
    };
  })(this));
  return this.models;
};`

**Comment by kurisutofu** [comment]
@hardikverma24 , I'm at work and can't check right now but could it be that it's because you didn't create Company class first?
I may be saying something stupid, I only had time to quickly glance.

**Comment by hardikverma24** [comment]
@kurisutofu I have that thing sorted out.....but I'm stuck at a new thing....in my models, wherever there is a targetKey defined in belongsToMany association, its throwing an error
`(node:12819) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'field' of undefined
    at new BelongsToMany (/home/springrole/toro/backend/node_modules/sequelize/lib/associations/belongs-to-many.js:134:71)
    at Function.belongsToMany (/home/springrole/toro/backend/node_modules/sequelize/lib/associations/mixin.js:64:25)
    at Function.Company.associate (/home/springrole/toro/backend/models/Company.js:133:17)
    at /home/springrole/toro/backend/models/index.js:33:40
    at Array.forEach (<anonymous>)
    at module.exports (/home/springrole/toro/backend/models/index.js:30:28)
    at module.exports (/home/springrole/toro/backend/index.js:38:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by kurisutofu** [comment]
@hardikverma24 , I believe this means you are not associating correctly a field for your Company table. Looks like you are associating as a BelongsToMany and I think it does not find the table to associate to.
Look into that association.

**Comment by nicolascava** [comment]
I'm sorry, but I close this issue because it's been months since the last message.
